export enum Currency {
  USD = 'USD',
}

export enum OrderStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

/**
 * CAPTURE - The merchant intends to capture payment immediately after
 *           the customer makes a payment.
 * AUTHORIZE - The merchant intends to authorize a payment and place
 *             funds on hold after the customer makes a payment.
 */
export enum Intent {
  CAPTURE = 'CAPTURE',
  AUTHORIZE = 'AUTHORIZE',
}

// Generated by https://quicktype.io
export interface CreateOrderResponse {
  id: string;
  status: string;
  payment_source: PaymentSource;
  links: Link[];
}

export interface Link {
  href: string;
  rel: string;
  method: string;
}

export interface PaymentSource {
  paypal: Paypal;
}

export interface Paypal {}
